/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateIdeaArgs } from "./CreateIdeaArgs";
import { UpdateIdeaArgs } from "./UpdateIdeaArgs";
import { DeleteIdeaArgs } from "./DeleteIdeaArgs";
import { IdeaCountArgs } from "./IdeaCountArgs";
import { IdeaFindManyArgs } from "./IdeaFindManyArgs";
import { IdeaFindUniqueArgs } from "./IdeaFindUniqueArgs";
import { Idea } from "./Idea";
import { IdeaService } from "../idea.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Idea)
export class IdeaResolverBase {
  constructor(
    protected readonly service: IdeaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Idea",
    action: "read",
    possession: "any",
  })
  async _ideasMeta(
    @graphql.Args() args: IdeaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Idea])
  @nestAccessControl.UseRoles({
    resource: "Idea",
    action: "read",
    possession: "any",
  })
  async ideas(@graphql.Args() args: IdeaFindManyArgs): Promise<Idea[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Idea, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Idea",
    action: "read",
    possession: "own",
  })
  async idea(@graphql.Args() args: IdeaFindUniqueArgs): Promise<Idea | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Idea)
  @nestAccessControl.UseRoles({
    resource: "Idea",
    action: "create",
    possession: "any",
  })
  async createIdea(@graphql.Args() args: CreateIdeaArgs): Promise<Idea> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Idea)
  @nestAccessControl.UseRoles({
    resource: "Idea",
    action: "update",
    possession: "any",
  })
  async updateIdea(@graphql.Args() args: UpdateIdeaArgs): Promise<Idea | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Idea)
  @nestAccessControl.UseRoles({
    resource: "Idea",
    action: "delete",
    possession: "any",
  })
  async deleteIdea(@graphql.Args() args: DeleteIdeaArgs): Promise<Idea | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
